version: "3.8"

services:
  redis:
    image: redis:6.2.1
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - erp
    restart: always
    volumes:
      - "redisdata:/data"
    environment:
      TZ: Asia/Shanghai
      REDIS_PASSWORD: "LigtepK.7N"
  mysql:
    image: mysql:5.7.33
    container_name: mysql
    ports:
      - 3306:3306
    networks:
      - erp
    volumes:
      - "mysqldata:/var/lib/mysql"
      - "./docs/jsh_erp.sql:/docker-entrypoint-initdb.d/jsh_erp.sql"
    environment:
      - "MYSQL_DATABASE=jsp_erp"
      - "MYSQL_ROOT_PASSWORD=LigtepK.7N"
      - "TZ=Asia/Shanghai"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=1
      --default-time-zone=+8:00

  app:
    build:
      context: jshERP-boot
      dockerfile: Dockerfile
    container_name: app
    networks:
      - erp
    ports:
      - 9999:9999
    depends_on:
      - mysql
      - redis
    restart: on-failure

  web:
    build:
      context: jshERP-web
      dockerfile: Dockerfile
    container_name: web
    networks:
      - erp
    depends_on:
      - app
    ports:
      - 80:80
    restart: on-failure

volumes:
  mysqldata:
  redisdata:

networks:
  erp: